import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt 

dat = pd.read_csv('tput.csv')
dat = dat.groupby(by=["Loss_pc"]).mean().reset_index()
loss_arr = np.array([0,1,3,6,12,18,27,36,45,50])
val_arr = np.divide(np.array(dat.BBR_goodput),1000)
plt.plot(loss_arr,val_arr, label="BBR")
val_arr = np.divide(np.array(dat.CUBIC_goodput),1000)
plt.plot(loss_arr,val_arr, label="CUBIC")
val_arr = np.divide(np.array(dat.Reno_goodput),1000)
plt.plot(loss_arr,val_arr, label="Reno")
val_arr = np.divide(np.array(dat.BBR1dot1_goodput),1000)
plt.plot(loss_arr,val_arr, label="BBR1.1")
val_arr = np.divide(np.array(dat.BBR1dot5_goodput),1000)
plt.plot(loss_arr,val_arr, label="BBR1.5")
plt.title("Goodput comparison against loss")
plt.xlabel("Loss percentage (%)")
plt.ylabel("Goodput (in Mbps)")
plt.legend(["BBR", "CUBIC","Reno","BBR1.1","BBR1.5"])
plt.show()

dat = pd.read_csv('retr.csv')
dat = dat.groupby(by=["Loss_pc"]).mean().reset_index()
val_arr = np.array(dat.BBR_retransmissions)
plt.plot(loss_arr,val_arr, label="BBR")
val_arr = np.array(dat.CUBIC_retransmissions)
plt.plot(loss_arr,val_arr, label="CUBIC")
val_arr = np.array(dat.Reno_retransmissions)
plt.plot(loss_arr,val_arr, label="Reno")
val_arr = np.array(dat.BBR1dot1_retransmissions)
plt.plot(loss_arr,val_arr, label="BBR1.1")
val_arr = np.array(dat.BBR1dot5_retransmissions)
plt.plot(loss_arr,val_arr, label="BBR1.5")
plt.title("Retransmissions comparison against loss")
plt.xlabel("Loss percentage (%)")
plt.ylabel("Number of retransmissions")
plt.legend(["BBR", "CUBIC","Reno","BBR1.1","BBR1.5"])
plt.show()